Repository TombEngine/TombEngine, pull requests merged in 2023-11, with the labels that each got.

#1222 Adngel Enemies Killing Camera fixes.
  TombEngine/Game/Lara/lara_struct.h
  TombEngine/Game/camera.cpp
  TombEngine/Game/control/box.cpp
  TombEngine/Objects/TR1/Entity/tr1_giant_mutant.cpp
  TombEngine/Objects/TR2/Entity/tr2_spear_guardian.cpp
  TombEngine/Objects/TR2/Entity/tr2_yeti.cpp
  TombEngine/Objects/TR3/Entity/tr3_trex.cpp
  TombEngine/Objects/TR3/Entity/tr3_trex.h
  TombEngine/Objects/TR4/Entity/tr4_big_scorpion.cpp
  TombEngine/Objects/TR4/Entity/tr4_setha.cpp
  TombEngine/Objects/TR4/Entity/tr4_setha.h
Labels: Gameplay, Fix, Code Refactor

#1244 Electric cleaner refactor
  TombEngine/Game/collision/collide_room.cpp
  TombEngine/Game/collision/collide_room.h
  TombEngine/Objects/TR3/Trap/ElectricCleaner.cpp
  TombEngine/Objects/TR3/Trap/ElectricCleaner.h
  TombEngine/Objects/TR3/tr3_objects.cpp
Labels: Code Refactor

#1259 TR3- gun turret
  TombEngine/Objects/TR3/Entity/TwinAutoGun.cpp
  TombEngine/Objects/TR3/Entity/TwinAutoGun.h
  TombEngine/Objects/TR3/tr3_objects.cpp
  TombEngine/Objects/TR5/Entity/AutoGun.cpp
  TombEngine/Objects/TR5/Entity/AutoGun.h
  TombEngine/Objects/TR5/tr5_objects.cpp
  TombEngine/Objects/game_object_ids.h
  TombEngine/Scripting/Internal/TEN/Objects/ObjectIDs.h
  TombEngine/TombEngine.vcxproj
Labels: In Review, Gameplay
