Repository TombEngine/TombEngine, pull requests merged in 2023-03, with the labels that each got.

#1024 Stranger1992/tr5 imp refactor
  TombEngine/Game/items.cpp
  TombEngine/Game/items.h
  TombEngine/Objects/TR5/Entity/tr5_imp.cpp
  TombEngine/Objects/TR5/tr5_objects.cpp
Labels: Gameplay

#1019 slamming door backport
  TombEngine/Objects/TR1/Trap/SlammingDoors.cpp
  TombEngine/Objects/TR1/Trap/SlammingDoors.h
  TombEngine/Objects/TR1/tr1_objects.cpp
  TombEngine/Objects/game_object_ids.h
  TombEngine/Scripting/Internal/TEN/Objects/ObjectIDs.h
  TombEngine/Sound/sound_effects.h
  TombEngine/TombEngine.vcxproj
Labels: Enhancement

#1016 HUD revisions tier 2
  TombEngine/Game/Hud/Hud.cpp
  TombEngine/Game/Hud/Hud.h
  TombEngine/Game/Hud/PickupSummary.cpp
  TombEngine/Game/Hud/PickupSummary.h
  TombEngine/Game/Hud/StatusBars.cpp
  TombEngine/Game/Hud/StatusBars.h
  TombEngine/Game/Lara/lara.h
  TombEngine/Game/Lara/lara_basic.cpp
  TombEngine/Game/Lara/lara_cheat.cpp
  TombEngine/Game/Lara/lara_helpers.cpp
  TombEngine/Game/Lara/lara_helpers.h
  TombEngine/Game/Lara/lara_initialise.cpp
  TombEngine/Game/Lara/lara_swim.cpp
  TombEngine/Game/control/box.cpp
  TombEngine/Game/control/control.cpp
  TombEngine/Game/gui.cpp
  TombEngine/Renderer/IndexBuffer/IndexBuffer.h
  TombEngine/Renderer/Renderer11.cpp
  TombEngine/Renderer/Renderer11.h
  TombEngine/Renderer/Renderer11Draw.cpp
  TombEngine/Renderer/Renderer11Draw2D.cpp
  TombEngine/Renderer/Renderer11DrawMenu.cpp
  TombEngine/Renderer/Renderer11Enums.h
  TombEngine/Renderer/Renderer11Helper.cpp
  TombEngine/TombEngine.vcxproj
Labels: Enhancement

#1021 automatic clear object camera at levelend
  TombEngine/Game/camera.cpp
  TombEngine/Game/camera.h
  TombEngine/Game/control/control.cpp
Labels: Bug, Fix

#1015 Implemented TR3 wasp mutant.
  Documentation/Changes.txt
  TombEngine/Game/control/box.h
  TombEngine/Game/effects/effects.cpp
  TombEngine/Game/effects/effects.h
  TombEngine/Objects/TR3/Entity/WaspMutant.cpp
  TombEngine/Objects/TR3/Entity/WaspMutant.h
  TombEngine/Objects/TR3/tr3_objects.cpp
  TombEngine/Objects/game_object_ids.h
  TombEngine/Renderer/Renderer11DrawEffect.cpp
  TombEngine/Scripting/Internal/TEN/Objects/ObjectIDs.h
  TombEngine/TombEngine.vcxproj
Labels: Enhancement
