Repository TombEngine/TombEngine, pull requests merged in 2023-08, with the labels that each got.

#1180 Fix animation when Lara's killed by TR3 train.
  TombEngine/Objects/TR3/Trap/train.cpp
Labels: Bug, Regression, Fix

#1179 Use OIS ParamList since default behaviour blocks the WIN key.
  TombEngine/Specific/Input/Input.cpp
Labels: Enhancement

#1185 Knife thrower fix
  Documentation/Changes.txt
  TombEngine/Objects/TR2/Entity/tr2_knife_thrower.cpp
Labels: Fix

#1183 Adngel crumbling platform
  TombEngine/Objects/Generic/Traps/crumblingPlatform.cpp
  TombEngine/Objects/Generic/Traps/crumblingPlatform.h
  TombEngine/Objects/Generic/generic_objects.cpp
  TombEngine/TombEngine.vcxproj
Labels: Gameplay, Floordata, Asset Issue

#1199 Adngel lua weapons functions
  TombEngine/Game/Lara/lara_struct.h
  TombEngine/Game/savegame.cpp
  TombEngine/Scripting/Internal/ReservedScriptNames.h
  TombEngine/Scripting/Internal/TEN/Flow/FlowHandler.cpp
  TombEngine/Scripting/Internal/TEN/Flow/InventoryItem/InventoryItem.cpp
  TombEngine/Scripting/Internal/TEN/Flow/InventoryItem/InventoryItem.h
  TombEngine/Scripting/Internal/TEN/Logic/LogicHandler.cpp
  TombEngine/Scripting/Internal/TEN/Objects/Lara/AmmoTypes.h
  TombEngine/Scripting/Internal/TEN/Objects/Lara/LaraObject.cpp
  TombEngine/Scripting/Internal/TEN/Objects/Lara/LaraObject.h
  TombEngine/Scripting/Internal/TEN/Objects/ObjectsHandler.cpp
  TombEngine/Scripting/Internal/TEN/Objects/Room/RoomFlags.h
  TombEngine/TombEngine.vcxproj
Labels: Lua, Fix

#1196 Adngel enemies Peru fixes
  TombEngine/Objects/TR1/Entity/tr1_bear.cpp
  TombEngine/Objects/TR1/Entity/tr1_wolf.cpp
Labels: Gameplay, Fix, Asset Issue

#1190 Adngel - Implement Swinging Blade
  TombEngine/Objects/TR1/Trap/SwingingBlade.cpp
  TombEngine/Objects/TR1/Trap/SwingingBlade.h
  TombEngine/Objects/TR1/tr1_objects.cpp
  TombEngine/Objects/TR4/Trap/tr4_stargate.cpp
  TombEngine/Objects/game_object_ids.h
  TombEngine/Scripting/Internal/TEN/Objects/ObjectIDs.h
  TombEngine/TombEngine.vcxproj
Labels: Gameplay, Asset Issue
