Repository TombEngine/TombEngine, pull requests merged in 2023-02, with the labels that each got.

#967 More lua funcs adngel
  Documentation/Changes.txt
  TombEngine/Game/camera.cpp
  TombEngine/Game/camera.h
  TombEngine/Scripting/Internal/ReservedScriptNames.h
  TombEngine/Scripting/Internal/TEN/Objects/Camera/CameraObject.cpp
  TombEngine/Scripting/Internal/TEN/Objects/Lara/LaraObject.cpp
  TombEngine/Scripting/Internal/TEN/Objects/Lara/LaraObject.h
  TombEngine/Scripting/Internal/TEN/Objects/Moveable/MoveableObject.cpp
  TombEngine/Scripting/Internal/TEN/Objects/Moveable/MoveableObject.h
Labels: Enhancement, Lua

#983 Tiger polishment adngel
  Documentation/Changes.txt
  TombEngine/Game/collision/collide_room.cpp
  TombEngine/Objects/TR3/Entity/tr3_tiger.cpp
  TombEngine/Objects/TR4/Entity/tr4_harpy.cpp
  TombEngine/Objects/TR5/Entity/tr5_lion.cpp
Labels: Enhancement, Gameplay

#970 Squash and stretch bubbles
  TombEngine/Game/Lara/lara_collide.cpp
  TombEngine/Game/Lara/lara_one_gun.cpp
  TombEngine/Game/control/control.cpp
  TombEngine/Game/effects/Electricity.cpp
  TombEngine/Game/effects/bubble.cpp
  TombEngine/Game/effects/bubble.h
  TombEngine/Game/effects/chaffFX.cpp
  TombEngine/Game/effects/chaffFX.h
  TombEngine/Game/effects/effects.cpp
  TombEngine/Game/effects/effects.h
  TombEngine/Game/effects/tomb4fx.cpp
  TombEngine/Game/effects/tomb4fx.h
  TombEngine/Game/missile.cpp
  TombEngine/Objects/Sink.h
  TombEngine/Objects/TR3/Vehicles/kayak.cpp
  TombEngine/Objects/TR3/Vehicles/rubber_boat.cpp
  TombEngine/Objects/TR3/Vehicles/upv.cpp
  TombEngine/Objects/TR5/Emitter/tr5_smoke_emitter.cpp
  TombEngine/Renderer/Renderer11DrawEffect.cpp
  TombEngine/Scripting/Internal/TEN/Objects/Sink/SinkObject.cpp
  TombEngine/Specific/setup.cpp
  TombEngine/TombEngine.vcxproj
  TombEngine/framework.h
Labels: Enhancement, Effect enchancement

#990 HUD revisions
  TombEngine/Game/Hud/Hud.cpp
  TombEngine/Game/Hud/Hud.h
  TombEngine/Game/Hud/PickupSummary.cpp
  TombEngine/Game/Hud/PickupSummary.h
  TombEngine/Game/Lara/lara_basic.cpp
  TombEngine/Game/Lara/lara_initialise.cpp
  TombEngine/Game/animation.cpp
  TombEngine/Game/control/control.cpp
  TombEngine/Game/gui.cpp
  TombEngine/Game/health.cpp
  TombEngine/Game/health.h
  TombEngine/Game/pickup/pickup.cpp
  TombEngine/Math/Objects/EulerAngles.cpp
  TombEngine/Math/Objects/EulerAngles.h
  TombEngine/Math/Objects/GameBoundingBox.cpp
  TombEngine/Math/Objects/GameBoundingBox.h
  TombEngine/Objects/TR4/Object/tr4_sarcophagus.cpp
  TombEngine/Objects/TR4/Vehicles/motorbike.cpp
  TombEngine/Renderer/Renderer11.cpp
  TombEngine/Renderer/Renderer11.h
  TombEngine/Renderer/Renderer11Draw.cpp
  TombEngine/Renderer/Renderer11Draw2D.cpp
  TombEngine/Renderer/Renderer11DrawMenu.cpp
  TombEngine/Renderer/Renderer11Enums.h
  TombEngine/Renderer/Renderer11Helper.cpp
  TombEngine/Renderer/Renderer11Init.cpp
  TombEngine/Renderer/Renderer11Settings.cpp
  TombEngine/Renderer/Renderer11String.cpp
  TombEngine/Specific/Input/Input.cpp
  TombEngine/Specific/level.cpp
  TombEngine/Specific/trutils.cpp
  TombEngine/Specific/trutils.h
  TombEngine/Specific/winmain.cpp
  TombEngine/TombEngine.vcxproj
Labels: Enhancement, Gameplay

#999 Fixed shiva taking damage when in stone
  Documentation/Changes.txt
  TombEngine/Game/Lara/lara_fire.cpp
  TombEngine/Game/control/los.cpp
  TombEngine/Game/control/lot.cpp
  TombEngine/Objects/TR3/Entity/Shiva.cpp
  TombEngine/Objects/TR3/Entity/Shiva.h
  TombEngine/Objects/TR3/tr3_objects.cpp
  TombEngine/TombEngine.vcxproj
Labels: Fix

#1005 Electric Cleaner with vectors adngel
  TombEngine/Game/collision/collide_room.cpp
  TombEngine/Game/collision/collide_room.h
  TombEngine/Game/control/box.cpp
  TombEngine/Game/control/box.h
  TombEngine/Objects/TR3/Trap/ElectricCleaner.cpp
  TombEngine/Objects/TR3/Trap/ElectricCleaner.h
  TombEngine/Objects/TR3/tr3_objects.cpp
  TombEngine/Objects/TR5/Object/tr5_pushableblock.cpp
  TombEngine/Objects/game_object_ids.h
  TombEngine/Scripting/Internal/TEN/Objects/ObjectIDs.h
  TombEngine/TombEngine.vcxproj
Labels: Bug, Enhancement, Gameplay, Fix

#1010 Fix big gun rocket exploding when spawned.
  Documentation/Changes.txt
  TombEngine/Objects/TR3/Vehicles/big_gun.cpp
Labels: Fix

#997 Fix tony not using boss effects.
  Documentation/Changes.txt
  TombEngine/Objects/TR3/Entity/tr3_tony.cpp
  TombEngine/Objects/TR3/Entity/tr3_tony.h
  TombEngine/Objects/TR3/tr3_objects.cpp
  TombEngine/TombEngine.vcxproj
Labels: Effect enchancement

#1004 Fix tr2 statue
  Documentation/Changes.txt
  TombEngine/Game/Lara/lara_struct.h
  TombEngine/Game/items.cpp
  TombEngine/Objects/TR2/Entity/tr2_spear_guardian.cpp
  TombEngine/Objects/TR2/Entity/tr2_spear_guardian.h
  TombEngine/Objects/TR2/Entity/tr2_sword_guardian.cpp
  TombEngine/Objects/TR2/Entity/tr2_sword_guardian.h
  TombEngine/Objects/TR2/tr2_objects.cpp
Labels: Fix, Effect enchancement

#996 Fix sophia ocb and added knockback effect.
  Documentation/Changes.txt
  TombEngine/Game/effects/tomb4fx.cpp
  TombEngine/Game/effects/tomb4fx.h
  TombEngine/Objects/TR3/Entity/SophiaLeigh.cpp
  TombEngine/Renderer/Renderer11DrawEffect.cpp
Labels: Fix

#998 Update drips, ripples, bubbles
  TombEngine/Game/Lara/lara.cpp
  TombEngine/Game/Lara/lara.h
  TombEngine/Game/Lara/lara_helpers.cpp
  TombEngine/Game/Lara/lara_helpers.h
  TombEngine/Game/Lara/lara_one_gun.cpp
  TombEngine/Game/Lara/lara_struct.h
  TombEngine/Game/control/control.cpp
  TombEngine/Game/control/flipeffect.cpp
  TombEngine/Game/effects/Blood.cpp
  TombEngine/Game/effects/Blood.h
  TombEngine/Game/effects/Electricity.cpp
  TombEngine/Game/effects/Electricity.h
  TombEngine/Game/effects/Ripple.cpp
  TombEngine/Game/effects/Ripple.h
  TombEngine/Game/effects/bubble.cpp
  TombEngine/Game/effects/bubble.h
  TombEngine/Game/effects/drip.cpp
  TombEngine/Game/effects/drip.h
  TombEngine/Game/effects/effects.cpp
  TombEngine/Game/effects/effects.h
  TombEngine/Game/effects/smoke.h
  TombEngine/Game/effects/tomb4fx.cpp
  TombEngine/Game/effects/tomb4fx.h
  TombEngine/Game/effects/weather.cpp
  TombEngine/Game/items.h
  TombEngine/Game/savegame.cpp
  TombEngine/Objects/Effects/tr5_electricity.cpp
  TombEngine/Objects/TR3/Vehicles/upv.cpp
  TombEngine/Objects/TR4/Object/tr4_scales.cpp
  TombEngine/Objects/TR5/Emitter/tr5_rats_emitter.cpp
  TombEngine/Renderer/Renderer11.h
  TombEngine/Renderer/Renderer11Draw.cpp
  TombEngine/Renderer/Renderer11DrawEffect.cpp
  TombEngine/Scripting/Internal/TEN/Objects/Lara/LaraObject.cpp
  TombEngine/Specific/setup.cpp
  TombEngine/TombEngine.vcxproj
Labels: Enhancement, Gameplay, Effect enchancement

#1017 Fix direction generation
  TombEngine/Math/Random.cpp
  TombEngine/Math/Random.h
Labels: Fix
