Repository TombEngine/TombEngine, pull requests merged in 2023-01, with the labels that each got.

#898 Rooms collector fixes
  TombEngine/Game/control/control.cpp
  TombEngine/Game/control/control.h
  TombEngine/Game/room.h
  TombEngine/Renderer/Renderer11.cpp
  TombEngine/Renderer/Renderer11.h
  TombEngine/Renderer/Renderer11Compatibility.cpp
  TombEngine/Renderer/Renderer11Debug.cpp
  TombEngine/Renderer/Renderer11Draw.cpp
  TombEngine/Renderer/Renderer11DrawMenu.cpp
  TombEngine/Renderer/Renderer11Frame.cpp
  TombEngine/Renderer/Renderer11Helper.cpp
  TombEngine/Renderer/Structures/RendererDoor.h
  TombEngine/Renderer/Structures/RendererLight.h
  TombEngine/Renderer/Structures/RendererRoom.h
  TombEngine/Scripting/Internal/TEN/Objects/Static/StaticObject.cpp
  TombEngine/TombEngine.vcxproj
  TombEngine/framework.h
  TombEngine/packages.config
Labels: Renderer

#944 Added obj->HitRoutine
  TombEngine/Game/Lara/lara_fire.cpp
  TombEngine/Game/Lara/lara_fire.h
  TombEngine/Game/control/box.cpp
  TombEngine/Game/control/box.h
  TombEngine/Game/items.cpp
  TombEngine/Game/items.h
  TombEngine/Objects/TR2/Entity/tr2_spear_guardian.cpp
  TombEngine/Objects/TR2/Entity/tr2_yeti.cpp
  TombEngine/Objects/TR3/Entity/tr3_shiva.cpp
  TombEngine/Objects/TR3/Entity/tr3_shiva.h
  TombEngine/Objects/TR3/tr3_objects.cpp
  TombEngine/Objects/TR4/Entity/tr4_baddy.cpp
  TombEngine/Objects/TR4/Entity/tr4_baddy.h
  TombEngine/Objects/TR4/Entity/tr4_big_scorpion.cpp
  TombEngine/Objects/TR4/tr4_objects.cpp
  TombEngine/Objects/TR5/Entity/tr5_roman_statue.cpp
  TombEngine/Objects/TR5/Entity/tr5_roman_statue.h
  TombEngine/Objects/TR5/tr5_objects.cpp
  TombEngine/Specific/setup.cpp
  TombEngine/Specific/setup.h
  TombEngine/TombEngine.vcxproj
Labels: Enhancement

#934 Lua new functions adngel
  Documentation/Changes.txt
  TombEngine/Math/Containers/GameVector.cpp
  TombEngine/Scripting/Internal/ReservedScriptNames.h
  TombEngine/Scripting/Internal/TEN/Misc/CameraTypes.h
  TombEngine/Scripting/Internal/TEN/Misc/Miscellanous.cpp
  TombEngine/Scripting/Internal/TEN/Misc/Miscellanous.h
  TombEngine/Scripting/Internal/TEN/Objects/Camera/CameraObject.cpp
  TombEngine/Scripting/Internal/TEN/Objects/Camera/CameraObject.h
  TombEngine/Scripting/Internal/TEN/Objects/Moveable/MoveableObject.cpp
  TombEngine/Scripting/Internal/TEN/Objects/Moveable/MoveableObject.h
  TombEngine/Specific/LevelCameraInfo.h
  TombEngine/Specific/level.cpp
  TombEngine/TombEngine.vcxproj
Labels: Enhancement, Gameplay, Lua, Fix

#952 Fix Big Rat death crash
  Documentation/Changes.txt
  TombEngine/Objects/TR1/Entity/tr1_big_rat.cpp
Labels: Gameplay, Fix

#949 LOTType refactor
  TombEngine/Game/control/box.cpp
  TombEngine/Game/control/lot.cpp
  TombEngine/Game/itemdata/creature_info.h
  TombEngine/Objects/TR1/tr1_objects.cpp
  TombEngine/Objects/TR2/Entity/tr2_spider.cpp
  TombEngine/Objects/TR2/tr2_objects.cpp
  TombEngine/Objects/TR3/tr3_objects.cpp
  TombEngine/Objects/TR4/tr4_objects.cpp
  TombEngine/Objects/TR5/tr5_objects.cpp
  TombEngine/Specific/setup.cpp
Labels: Enhancement, Gameplay

#946 OG explosion effect, fixed TR5_explosion item, seth missiles
  TombEngine/Game/Lara/lara_one_gun.cpp
  TombEngine/Game/effects/effects.cpp
  TombEngine/Game/effects/effects.h
  TombEngine/Objects/Effects/enemy_missile.cpp
  TombEngine/Objects/TR4/Entity/tr4_setha.cpp
  TombEngine/Objects/TR5/Trap/tr5_explosion.cpp
Labels: Enhancement, OG, Fix

#959 fixed Demigod2, fixed TR4 enemy missiles mesh
  TombEngine/Objects/Effects/enemy_missile.cpp
  TombEngine/Objects/TR4/Entity/tr4_demigod.cpp
Labels: Enhancement, Gameplay, Fix

#933 Added lizard and punaboss from TR3
  Documentation/Changes.txt
  TombEngine/Game/Lara/lara_fire.cpp
  TombEngine/Game/animation.cpp
  TombEngine/Game/animation.h
  TombEngine/Game/control/box.cpp
  TombEngine/Game/control/box.h
  TombEngine/Game/effects/spark.cpp
  TombEngine/Game/effects/spark.h
  TombEngine/Game/items.cpp
  TombEngine/Game/items.h
  TombEngine/Game/misc.cpp
  TombEngine/Game/room.cpp
  TombEngine/Math/Geometry.cpp
  TombEngine/Math/Geometry.h
  TombEngine/Objects/Effects/Boss.cpp
  TombEngine/Objects/Effects/Boss.h
  TombEngine/Objects/Generic/Doors/generic_doors.cpp
  TombEngine/Objects/TR1/Entity/tr1_winged_mutant.cpp
  TombEngine/Objects/TR2/Entity/tr2_eagle_or_crow.cpp
  TombEngine/Objects/TR2/tr2_objects.cpp
  TombEngine/Objects/TR3/Entity/Lizard.cpp
  TombEngine/Objects/TR3/Entity/Lizard.h
  TombEngine/Objects/TR3/Entity/PunaBoss.cpp
  TombEngine/Objects/TR3/Entity/PunaBoss.h
  TombEngine/Objects/TR3/Entity/tr3_mp_gun.cpp
  TombEngine/Objects/TR3/Entity/tr3_mp_stick.cpp
  TombEngine/Objects/TR3/Entity/tr3_raptor.cpp
  TombEngine/Objects/TR3/Entity/tr3_shiva.cpp
  TombEngine/Objects/TR3/Entity/tr3_shiva.h
  TombEngine/Objects/TR3/tr3_objects.cpp
  TombEngine/Objects/TR4/Entity/tr4_baddy.cpp
  TombEngine/Objects/TR4/Entity/tr4_big_scorpion.cpp
  TombEngine/Objects/TR4/Entity/tr4_guide.cpp
  TombEngine/Objects/TR4/Entity/tr4_troops.cpp
  TombEngine/Objects/TR4/Entity/tr4_von_croy.cpp
  TombEngine/Objects/TR4/Entity/tr4_wild_boar.cpp
  TombEngine/Objects/TR4/tr4_objects.cpp
  TombEngine/Objects/TR5/tr5_objects.cpp
  TombEngine/Objects/Utils/object_helper.cpp
  TombEngine/Objects/Utils/object_helper.h
  TombEngine/Objects/game_object_ids.h
  TombEngine/Scripting/Internal/TEN/Objects/ObjectIDs.h
  TombEngine/Specific/setup.h
  TombEngine/TombEngine.vcxproj
Labels: Enhancement, Gameplay

#955 Add fixed shadow and dropped pickup positions
  Documentation/Changes.txt
  TombEngine/Game/animation.cpp
  TombEngine/Game/animation.h
  TombEngine/Game/control/box.cpp
  TombEngine/Game/control/box.h
  TombEngine/Game/pickup/pickup.cpp
  TombEngine/Game/pickup/pickup.h
  TombEngine/Math/Containers/GameBoundingBox.cpp
  TombEngine/Math/Containers/GameBoundingBox.h
  TombEngine/Math/Geometry.cpp
  TombEngine/Math/Geometry.h
  TombEngine/Objects/TR5/Entity/tr5_cyborg.cpp
  TombEngine/Renderer/Renderer11.h
  TombEngine/Renderer/Renderer11Draw.cpp
Labels: Renderer, Gameplay

#961 Save vec3 rotation color
  TombEngine/Game/gui.cpp
  TombEngine/Game/savegame.cpp
  TombEngine/Scripting/Include/ScriptInterfaceGame.h
  TombEngine/Scripting/Internal/ReservedScriptNames.h
  TombEngine/Scripting/Internal/TEN/Logic/LogicHandler.cpp
  TombEngine/Scripting/Internal/TEN/Logic/LogicHandler.h
  TombEngine/Scripting/Internal/TEN/Objects/Moveable/MoveableObject.cpp
  TombEngine/Scripting/Internal/TEN/Rotation/Rotation.cpp
  TombEngine/Scripting/Internal/TEN/Rotation/Rotation.h
  TombEngine/Specific/savegame/flatbuffers/ten_savegame_generated.h
  TombEngine/Specific/savegame/schema/ten_savegame.fbs
Labels: Enhancement, Lua

#951 AxisAngle class
  TombEngine/Game/Lara/lara.cpp
  TombEngine/Game/Lara/lara_struct.h
  TombEngine/Game/Lara/lara_tests.h
  TombEngine/Math/Constants.h
  TombEngine/Math/Geometry.cpp
  TombEngine/Math/Geometry.h
  TombEngine/Math/Legacy.cpp
  TombEngine/Math/Legacy.h
  TombEngine/Math/Math.h
  TombEngine/Math/Objects/AxisAngle.cpp
  TombEngine/Math/Objects/AxisAngle.h
  TombEngine/Math/Objects/EulerAngles.cpp
  TombEngine/Math/Objects/EulerAngles.h
  TombEngine/Math/Objects/GameBoundingBox.cpp
  TombEngine/Math/Objects/GameBoundingBox.h
  TombEngine/Math/Objects/GameVector.cpp
  TombEngine/Math/Objects/GameVector.h
  TombEngine/Math/Objects/Pose.cpp
  TombEngine/Math/Objects/Pose.h
  TombEngine/Math/Objects/Vector2i.cpp
  TombEngine/Math/Objects/Vector2i.h
  TombEngine/Math/Objects/Vector3i.cpp
  TombEngine/Math/Objects/Vector3i.h
  TombEngine/Scripting/Internal/TEN/Misc/Miscellanous.cpp
  TombEngine/Scripting/Internal/TEN/Misc/Miscellanous.h
  TombEngine/Scripting/Internal/TEN/Rotation/Rotation.h
  TombEngine/TombEngine.vcxproj
Labels: Enhancement, Math

#957 Fix tr5 roman statue
  Documentation/Changes.txt
  TombEngine/Game/Lara/lara_one_gun.cpp
  TombEngine/Game/effects/spark.cpp
  TombEngine/Objects/TR5/Entity/tr5_roman_statue.cpp
  TombEngine/Objects/TR5/tr5_objects.cpp
Labels: Enhancement, Gameplay, Fix

#968 Fix puna boss dead smoke crash
  TombEngine/Objects/Effects/Boss.cpp
Labels: Fix, Effect enchancement

#966 Add floor/ceiling normal getter functions
  TombEngine/Game/Lara/lara_helpers.cpp
  TombEngine/Game/Lara/lara_tests.cpp
  TombEngine/Math/Geometry.cpp
  TombEngine/Math/Geometry.h
Labels: Enhancement, Math

#943 Fix tr5 twogun Laser guy
  TombEngine/Game/Lara/lara_fire.cpp
  TombEngine/Game/Lara/lara_fire.h
  TombEngine/Game/control/control.cpp
  TombEngine/Game/control/los.cpp
  TombEngine/Game/effects/Electricity.cpp
  TombEngine/Game/effects/Electricity.h
  TombEngine/Game/effects/lightning.cpp
  TombEngine/Game/effects/lightning.h
  TombEngine/Objects/Effects/flame_emitters.cpp
  TombEngine/Objects/TR3/Entity/PunaBoss.cpp
  TombEngine/Objects/TR4/Object/tr4_obelisk.cpp
  TombEngine/Objects/TR5/Entity/HeavyGuard.cpp
  TombEngine/Objects/TR5/Entity/HeavyGuard.h
  TombEngine/Objects/TR5/Entity/tr5_cyborg.cpp
  TombEngine/Objects/TR5/Entity/tr5_laser_head.cpp
  TombEngine/Objects/TR5/Entity/tr5_laserhead_info.h
  TombEngine/Objects/TR5/Entity/tr5_roman_statue.cpp
  TombEngine/Objects/TR5/tr5_objects.cpp
  TombEngine/Renderer/Renderer11.h
  TombEngine/Renderer/Renderer11Draw.cpp
  TombEngine/Renderer/Renderer11DrawEffect.cpp
  TombEngine/Scripting/Internal/TEN/Effects/EffectsFunctions.cpp
  TombEngine/Scripting/Internal/TEN/Logic/LogicHandler.cpp
  TombEngine/Sound/sound_effects.h
  TombEngine/TombEngine.vcxproj
Labels: Enhancement, Renderer, Gameplay, Fix

#974 Fixed fire damage on puna
  Documentation/Changes.txt
  TombEngine/Game/Lara/lara_one_gun.cpp
  TombEngine/Game/effects/spark.cpp
  TombEngine/Game/effects/spark.h
  TombEngine/Game/items.cpp
  TombEngine/Game/items.h
  TombEngine/Objects/TR3/Entity/PunaBoss.cpp
  TombEngine/Objects/TR5/Entity/tr5_roman_statue.cpp
Labels: Fix

#969 Added Sophia Leigh
  Documentation/Changes.txt
  TombEngine/Game/Lara/lara_one_gun.cpp
  TombEngine/Game/animation.cpp
  TombEngine/Game/animation.h
  TombEngine/Game/control/box.cpp
  TombEngine/Game/control/box.h
  TombEngine/Game/control/lot.cpp
  TombEngine/Game/effects/effects.cpp
  TombEngine/Game/effects/explosion.cpp
  TombEngine/Game/effects/tomb4fx.cpp
  TombEngine/Game/effects/tomb4fx.h
  TombEngine/Objects/Effects/Boss.cpp
  TombEngine/Objects/Effects/Boss.h
  TombEngine/Objects/Effects/enemy_missile.cpp
  TombEngine/Objects/Effects/enemy_missile.h
  TombEngine/Objects/TR3/Entity/SophiaLeigh.cpp
  TombEngine/Objects/TR3/Entity/SophiaLeigh.h
  TombEngine/Objects/TR3/Entity/tr3_cobra.cpp
  TombEngine/Objects/TR3/Entity/tr3_sophia.cpp
  TombEngine/Objects/TR3/Entity/tr3_sophia.h
  TombEngine/Objects/TR3/Entity/tr3_tony.cpp
  TombEngine/Objects/TR3/boss.h
  TombEngine/Objects/TR3/tr3_objects.cpp
  TombEngine/Objects/TR4/Entity/tr4_baddy.cpp
  TombEngine/Objects/TR4/Entity/tr4_demigod.cpp
  TombEngine/Objects/TR4/Entity/tr4_wraith.cpp
  TombEngine/Objects/TR4/Object/tr4_senet.cpp
  TombEngine/Objects/TR4/Trap/tr4_mine.cpp
  TombEngine/Objects/TR5/Entity/tr5_laser_head.cpp
  TombEngine/Objects/TR5/Entity/tr5_roman_statue.cpp
  TombEngine/Objects/TR5/Object/tr5_missile.cpp
  TombEngine/Objects/TR5/Trap/tr5_explosion.cpp
  TombEngine/Objects/game_object_ids.h
  TombEngine/Renderer/Renderer11DrawEffect.cpp
  TombEngine/Scripting/Internal/TEN/Effects/EffectsFunctions.cpp
  TombEngine/Scripting/Internal/TEN/Objects/ObjectIDs.h
  TombEngine/Specific/setup.h
  TombEngine/TombEngine.vcxproj
Labels: Enhancement, Gameplay

#977 Draw holsters for shadow and bypass skin / braid / joints if they don't exist
  Documentation/Changes.txt
  TombEngine/Game/Lara/lara_initialise.cpp
  TombEngine/Renderer/Renderer11.h
  TombEngine/Renderer/Renderer11Compatibility.cpp
  TombEngine/Renderer/Renderer11Draw.cpp
  TombEngine/Renderer/Renderer11Helper.cpp
  TombEngine/Renderer/Renderer11Lara.cpp
Labels: Renderer
