Repository TombEngine/TombEngine, pull requests merged in 2023-12, with the labels that each got.

#1256 Adngel varied fixes
  TombEngine/Game/Lara/lara.h
  TombEngine/Game/Lara/lara_fire.cpp
  TombEngine/Game/Lara/lara_flare.cpp
  TombEngine/Game/Lara/lara_tests.cpp
  TombEngine/Game/camera.cpp
  TombEngine/Game/control/box.cpp
  TombEngine/Game/pickup/pickup.cpp
  TombEngine/Objects/Effects/flame_emitters.cpp
  TombEngine/Objects/Generic/Object/Pushable/PushableCollision.cpp
  TombEngine/Objects/Generic/Object/Pushable/PushableStates.cpp
  TombEngine/Objects/Generic/Object/burning_torch.cpp
Labels: In Review, Fix

#1270 Soft intelligent object collision
  TombEngine/Game/collision/collide_item.cpp
  TombEngine/Game/collision/collide_item.h
  TombEngine/Math/Objects/Vector3i.cpp
  TombEngine/Math/Objects/Vector3i.h
Labels: Enhancement, Gameplay

#1277 Bridge refactor
  TombEngine/Game/Lara/lara_overhang.cpp
  TombEngine/Game/Setup.cpp
  TombEngine/Game/Setup.h
  TombEngine/Game/collision/floordata.cpp
  TombEngine/Game/itemdata/itemdata.h
  TombEngine/Game/items.cpp
  TombEngine/Game/items.h
  TombEngine/Game/room.cpp
  TombEngine/Game/savegame.cpp
  TombEngine/Objects/Generic/Object/BridgeObject.cpp
  TombEngine/Objects/Generic/Object/BridgeObject.h
  TombEngine/Objects/Generic/Object/Pushable/PushableCollision.cpp
  TombEngine/Objects/Generic/Object/Pushable/PushableInfo.cpp
  TombEngine/Objects/Generic/Object/Pushable/PushableInfo.h
  TombEngine/Objects/Generic/Object/generic_bridge.cpp
  TombEngine/Objects/Generic/Object/generic_bridge.h
  TombEngine/Objects/Generic/Object/generic_trapdoor.cpp
  TombEngine/Objects/Generic/Object/generic_trapdoor.h
  TombEngine/Objects/Generic/Traps/crumblingPlatform.cpp
  TombEngine/Objects/Generic/Traps/crumblingPlatform.h
  TombEngine/Objects/Generic/Traps/falling_block.cpp
  TombEngine/Objects/Generic/Traps/falling_block.h
  TombEngine/Objects/Generic/generic_objects.cpp
  TombEngine/Objects/TR5/Object/tr5_expandingplatform.cpp
  TombEngine/Objects/TR5/Object/tr5_expandingplatform.h
  TombEngine/Objects/TR5/Object/tr5_raisingblock.cpp
  TombEngine/Objects/TR5/Object/tr5_raisingblock.h
  TombEngine/Objects/TR5/Object/tr5_twoblockplatform.cpp
  TombEngine/Objects/TR5/Object/tr5_twoblockplatform.h
  TombEngine/Objects/TR5/tr5_objects.cpp
  TombEngine/Objects/Utils/object_helper.cpp
  TombEngine/Scripting/Internal/TEN/Objects/Moveable/MoveableObject.cpp
  TombEngine/Specific/level.cpp
  TombEngine/Specific/level.h
  TombEngine/TombEngine.vcxproj
Labels: Enhancement, Code Refactor

#1297 Get game status
  TombEngine/Game/control/control.cpp
  TombEngine/Game/control/control.h
  TombEngine/Scripting/Include/Flow/ScriptInterfaceFlowHandler.h
  TombEngine/Scripting/Internal/ReservedScriptNames.h
  TombEngine/Scripting/Internal/TEN/Flow/FlowHandler.cpp
  TombEngine/Scripting/Internal/TEN/Flow/FlowHandler.h
  TombEngine/Scripting/Internal/TEN/Flow/GameStatuses.h
  TombEngine/TombEngine.vcxproj
Labels: Lua

#1296 Pick objects by cursor
  Documentation/Changes.txt
  TombEngine/Game/control/los.cpp
  TombEngine/Game/control/los.h
  TombEngine/Objects/TR3/Entity/PunaBoss.cpp
  TombEngine/Objects/TR5/Entity/HeavyGuard.cpp
  TombEngine/Objects/TR5/Entity/tr5_laser_head.cpp
  TombEngine/Renderer/Renderer11.h
  TombEngine/Renderer/Renderer11Helper.cpp
  TombEngine/Scripting/Internal/ReservedScriptNames.h
  TombEngine/Scripting/Internal/TEN/Util/Util.cpp
  TombEngine/Scripting/Internal/TEN/View/ViewHandler.cpp
Labels: Lua

#1301 Lara start position handling
  Documentation/Changes.txt
  TombEngine/Game/Lara/lara_initialise.cpp
  TombEngine/Game/Lara/lara_initialise.h
  TombEngine/Game/control/control.cpp
  TombEngine/Game/control/flipeffect.cpp
  TombEngine/Game/control/trigger.cpp
  TombEngine/Scripting/Internal/TEN/Flow/FlowHandler.cpp
  TombEngine/Scripting/Internal/TEN/Flow/FlowHandler.h
Labels: Gameplay
