Repository TombEngine/TombEngine, pull requests merged in 2024-10, with the labels that each got.

#1386 Allow more access to Moveable joint info in Lua
  CHANGELOG.md
  TombEngine/Scripting/Internal/ReservedScriptNames.h
  TombEngine/Scripting/Internal/TEN/Objects/Moveable/MoveableObject.cpp
  TombEngine/Scripting/Internal/TEN/Objects/Moveable/MoveableObject.h
Labels: Enhancement

#1395 Changed/Fixed enemy jeep behaviour
  .github/ISSUE_TEMPLATE/bug_report.yaml
  TombEngine/Game/Setup.cpp
  TombEngine/Game/Setup.h
  TombEngine/Game/collision/collide_item.cpp
  TombEngine/Game/control/box.cpp
  TombEngine/Game/control/box.h
  TombEngine/Game/control/lot.cpp
  TombEngine/Game/effects/effects.cpp
  TombEngine/Objects/TR3/Entity/FishSwarm.cpp
  TombEngine/Objects/TR3/Entity/SophiaLeigh.cpp
  TombEngine/Objects/TR4/Entity/tr4_baddy.cpp
  TombEngine/Objects/TR4/Entity/tr4_enemy_jeep.cpp
  TombEngine/Objects/TR4/Entity/tr4_enemy_jeep.h
  TombEngine/Objects/TR4/tr4_objects.cpp
Labels: Enhancement, Fix

#1377 Adngel smoke emitter update
  CHANGELOG.md
  TombEngine/Game/effects/effects.cpp
  TombEngine/Game/effects/footprint.cpp
  TombEngine/Objects/Generic/Object/Pushable/PushableSound.cpp
  TombEngine/Objects/TR5/Emitter/tr5_smoke_emitter.cpp
  TombEngine/Objects/TR5/Emitter/tr5_smoke_emitter.h
  TombEngine/Objects/TR5/tr5_objects.cpp
  TombEngine/Renderer/RendererDrawEffect.cpp
  TombEngine/Sound/sound_effects.h
  TombEngine/TombEngine.vcxproj
Labels: Enhancement, Fix, Code Refactor

#1434 Fixed bitwise for itemStatus
  TombEngine/Game/items.h
  TombEngine/Objects/Generic/Object/objects.cpp
  TombEngine/Objects/TR1/Entity/SkateboardKid.cpp
  TombEngine/Objects/TR2/Entity/tr2_skidman.cpp
  TombEngine/Objects/TR2/Entity/tr2_spear_guardian.cpp
  TombEngine/Objects/TR2/Entity/tr2_sword_guardian.cpp
  TombEngine/Objects/TR3/Entity/Shiva.cpp
  TombEngine/Objects/TR4/Entity/tr4_dog.cpp
  TombEngine/Objects/TR4/Entity/tr4_mummy.cpp
  TombEngine/Objects/TR4/Entity/tr4_skeleton.cpp
  TombEngine/Objects/TR4/Trap/tr4_cog.cpp
  TombEngine/Objects/TR5/Entity/tr5_larson.cpp
Labels: Fix
