Repository TombEngine/TombEngine, pull requests merged in 2024-08, with the labels that each got.

#1346 Raptor upgrade
  TombEngine/Game/control/box.cpp
  TombEngine/Game/misc.cpp
  TombEngine/Game/misc.h
  TombEngine/Objects/TR3/Entity/tr3_raptor.cpp
  TombEngine/Objects/TR3/tr3_objects.cpp
Labels: Enhancement, Gameplay

#1393 Rework menu option looping
  CHANGELOG.md
  Scripts/SystemStrings.lua
  TombEngine/Game/gui.cpp
  TombEngine/Game/gui.h
  TombEngine/Renderer/RendererDrawMenu.cpp
  TombEngine/Scripting/Internal/LanguageScript.h
  TombEngine/Specific/Input/Input.cpp
  TombEngine/Specific/configuration.cpp
  TombEngine/Specific/configuration.h
Labels: UI, Usability, Code Refactor

#1392 Seal Mutant Port
  CHANGELOG.md
  Documentation/doc/4 enums/Objects.ObjID.html
  TombEngine/Game/control/control.cpp
  TombEngine/Game/effects/tomb4fx.cpp
  TombEngine/Game/effects/tomb4fx.h
  TombEngine/Game/itemdata/creature_info.h
  TombEngine/Game/people.cpp
  TombEngine/Objects/TR3/Entity/Lizard.cpp
  TombEngine/Objects/TR3/Entity/SealMutant.cpp
  TombEngine/Objects/TR3/Entity/SealMutant.h
  TombEngine/Objects/TR3/Entity/TwinAutoGun.cpp
  TombEngine/Objects/TR3/Entity/tr3_flamethrower.cpp
  TombEngine/Objects/TR3/tr3_objects.cpp
  TombEngine/Objects/game_object_ids.h
  TombEngine/Scripting/Internal/TEN/Objects/ObjectIDs.h
  TombEngine/TombEngine.vcxproj
Labels: Enhancement, In Review
