Repository TombEngine/TombEngine, pull requests merged in 2024-04, with the labels that each got.

#1337 TR4 squishy block 1 + 2
  TombEngine/Game/collision/collide_item.cpp
  TombEngine/Game/misc.cpp
  TombEngine/Game/misc.h
  TombEngine/Objects/TR3/Trap/ElectricCleaner.cpp
  TombEngine/Objects/TR4/Trap/SquishyBlock.cpp
  TombEngine/Objects/TR4/Trap/SquishyBlock.h
  TombEngine/Objects/TR4/tr4_objects.cpp
  TombEngine/Objects/game_object_ids.h
  TombEngine/Scripting/Internal/TEN/Objects/ObjectIDs.h
  TombEngine/Specific/level.cpp
  TombEngine/TombEngine.vcxproj
Labels: Enhancement

#1343 Use real bounding box tests for GetCollidedObjects
  Documentation/Changes.txt
  Documentation/doc/2 classes/Objects.Moveable.html
  Documentation/output.xml
  TombEngine/Game/Lara/lara_collide.cpp
  TombEngine/Game/Lara/lara_flare.cpp
  TombEngine/Game/Lara/lara_initialise.cpp
  TombEngine/Game/Lara/lara_one_gun.cpp
  TombEngine/Game/Lara/lara_tests.cpp
  TombEngine/Game/collision/collide_item.cpp
  TombEngine/Game/collision/collide_item.h
  TombEngine/Game/pickup/pickup.cpp
  TombEngine/Math/Geometry.cpp
  TombEngine/Math/Geometry.h
  TombEngine/Math/Math.cpp
  TombEngine/Objects/Effects/flame_emitters.cpp
  TombEngine/Objects/Effects/tr5_electricity.cpp
  TombEngine/Objects/Generic/Object/Pushable/PushableCollision.cpp
  TombEngine/Objects/Generic/Object/burning_torch.cpp
  TombEngine/Objects/TR1/Entity/SkateboardKid.cpp
  TombEngine/Objects/TR3/Trap/ElectricCleaner.cpp
  TombEngine/Objects/TR3/Vehicles/kayak.cpp
  TombEngine/Objects/TR4/Trap/SpikyWall.cpp
  TombEngine/Objects/TR5/Shatter/tr5_smashobject.cpp
  TombEngine/Objects/TR5/Trap/tr5_explosion.cpp
  TombEngine/Scripting/Internal/TEN/Objects/Moveable/MoveableObject.cpp
  TombEngine/Scripting/Internal/TEN/Objects/ObjectsHandler.cpp
Labels: Code Refactor

#1355 Adngel small fixes
  TombEngine/Objects/TR2/Entity/tr2_skidman.cpp
  TombEngine/Objects/TR2/Entity/tr2_worker_shotgun.cpp
Labels: In Development, Gameplay, Fix
